-- generated by scripts/compile-model.py from models/ -- do not edit
--
-- Regenerate with `make model`. CI runs `make model-check`, so a hand edit here
-- fails the build rather than silently drifting from the Toolkit YAML.

\set ON_ERROR_STOP on

-- A CDF schema space is a PostgreSQL schema. Instance spaces are NOT schemas: they
-- are the value of the `space` column on every row, which is what DMS means by them.
CREATE SCHEMA IF NOT EXISTS cdf_cdm;
CREATE SCHEMA IF NOT EXISTS cdf_idm;
CREATE SCHEMA IF NOT EXISTS dm_dom_well_production;
CREATE SCHEMA IF NOT EXISTS dm_sol_production_analytics;

-- Containers become Iceberg tables. Unversioned: they are the durable contract.

CREATE TABLE IF NOT EXISTS cdf_cdm.cognite_asset (
    space                            text NOT NULL,
    node_external_id                 text NOT NULL,
    asset_hierarchy_parent           text,
    asset_hierarchy_root             text,
    asset_hierarchy_path             text[],
    asset_hierarchy_path_last_updated_time timestamptz,
    asset_class                      text,
    type                             text,
    deleted                          boolean NOT NULL DEFAULT false
)
USING iceberg
WITH (
      out_of_range_values = 'error',
      max_snapshot_age = 604800
);

CREATE TABLE IF NOT EXISTS cdf_cdm.cognite_asset_type (
    space                            text NOT NULL,
    node_external_id                 text NOT NULL,
    code                             text,
    asset_class                      text,
    deleted                          boolean NOT NULL DEFAULT false
)
USING iceberg
WITH (
      out_of_range_values = 'error',
      max_snapshot_age = 604800
);

CREATE TABLE IF NOT EXISTS cdf_cdm.cognite_describable (
    space                            text NOT NULL,
    node_external_id                 text NOT NULL,
    name                             text,
    description                      text,
    tags                             text[],
    aliases                          text[],
    deleted                          boolean NOT NULL DEFAULT false
)
USING iceberg
WITH (
      out_of_range_values = 'error',
      max_snapshot_age = 604800
);

CREATE TABLE IF NOT EXISTS cdf_cdm.cognite_schedulable (
    space                            text NOT NULL,
    node_external_id                 text NOT NULL,
    start_time                       timestamptz,
    end_time                         timestamptz,
    scheduled_start_time             timestamptz,
    scheduled_end_time               timestamptz,
    deleted                          boolean NOT NULL DEFAULT false
)
USING iceberg
WITH (
      out_of_range_values = 'error',
      max_snapshot_age = 604800
);

CREATE TABLE IF NOT EXISTS cdf_cdm.cognite_sourceable (
    space                            text NOT NULL,
    node_external_id                 text NOT NULL,
    source_id                        text,
    source_context                   text,
    source_created_time              timestamptz,
    source_updated_time              timestamptz,
    deleted                          boolean NOT NULL DEFAULT false
)
USING iceberg
WITH (
      out_of_range_values = 'error',
      max_snapshot_age = 604800
);

CREATE TABLE IF NOT EXISTS cdf_idm.cognite_maintenance_order (
    space                            text NOT NULL,
    node_external_id                 text NOT NULL,
    main_asset                       text,
    type                             text,
    status                           text,
    priority                         integer,
    priority_description             text,
    deleted                          boolean NOT NULL DEFAULT false
)
USING iceberg
WITH (
      out_of_range_values = 'error',
      max_snapshot_age = 604800
);

CREATE TABLE IF NOT EXISTS dm_dom_well_production.asset (
    space                            text NOT NULL,
    node_external_id                 text NOT NULL,
    asset_type                       text NOT NULL,
    well_id                          text,
    field_code                       text,
    well_type                        text,
    spud_date                        date,
    water_depth_m                    double precision,
    total_depth_m                    double precision,
    completion_type                  text,
    deleted                          boolean NOT NULL DEFAULT false
)
USING iceberg
WITH (
      out_of_range_values = 'error',
      max_snapshot_age = 604800
);

CREATE TABLE IF NOT EXISTS dm_dom_well_production.production_measurement (
    space                            text NOT NULL,
    record_id                        text NOT NULL,
    wellbore                         text NOT NULL,
    measured_at                      timestamptz NOT NULL,
    oil_rate_bpd                     double precision,
    gas_rate_mscfd                   double precision,
    water_rate_bpd                   double precision,
    tubing_head_pressure_bar         double precision,
    choke_percent                    double precision,
    quality                          text
)
USING iceberg
WITH (
      partition_by = 'month(measured_at)',
      out_of_range_values = 'error',
      max_snapshot_age = 86400
);

CREATE TABLE IF NOT EXISTS dm_dom_well_production.well_intervention (
    space                            text NOT NULL,
    node_external_id                 text NOT NULL,
    intervention_type                text,
    estimated_uplift_bpd             double precision,
    deleted                          boolean NOT NULL DEFAULT false
)
USING iceberg
WITH (
      out_of_range_values = 'error',
      max_snapshot_age = 604800
);

CREATE TABLE IF NOT EXISTS dm_sol_production_analytics.well_production_daily (
    space                            text NOT NULL,
    node_external_id                 text NOT NULL,
    production_date                  date NOT NULL,
    wellbore                         text NOT NULL,
    well                             text,
    field                            text,
    well_name                        text,
    field_name                       text,
    oil_bbl                          double precision,
    gas_mscf                         double precision,
    water_bbl                        double precision,
    water_cut_pct                    double precision,
    gas_oil_ratio                    double precision,
    avg_tubing_head_pressure_bar     double precision,
    uptime_hours                     double precision,
    reading_count                    bigint,
    intervention_count               bigint,
    computed_at                      timestamptz NOT NULL,
    deleted                          boolean NOT NULL DEFAULT false
)
USING iceberg
WITH (
      partition_by = 'month(production_date)',
      out_of_range_values = 'error',
      max_snapshot_age = 604800
);

-- Views become PostgreSQL views. Versioned, with `implements` already flattened.

-- Reverse relations deliberately produce NO column: a correlated array subquery on

-- every scan would wreck both the view and DuckDB's ability to read the Parquet.

-- Connections live in semantic.view_properties and are joined on demand.

CREATE OR REPLACE VIEW cdf_cdm.cognite_asset_type_v1 AS
SELECT
  n.space,
  n.node_external_id,
  c1.name,
  c1.description,
  n.code
  FROM cdf_cdm.cognite_asset_type n
  LEFT JOIN cdf_cdm.cognite_describable c1 USING (space, node_external_id)
 WHERE NOT n.deleted;

CREATE OR REPLACE VIEW dm_dom_well_production.asset_v1 AS
SELECT
  n.space,
  n.node_external_id,
  c1.name,
  c1.description,
  c1.tags AS labels,
  c1.aliases,
  c2.source_id,
  c2.source_context,
  c2.source_created_time,
  c3.asset_hierarchy_parent AS parent,
  c3.asset_hierarchy_root AS root,
  c3.asset_hierarchy_path AS path,
  c3.type,
  n.asset_type,
  n.well_id,
  n.field_code,
  n.well_type,
  n.spud_date,
  n.water_depth_m,
  n.total_depth_m,
  n.completion_type
  FROM dm_dom_well_production.asset n
  LEFT JOIN cdf_cdm.cognite_describable c1 USING (space, node_external_id)
  LEFT JOIN cdf_cdm.cognite_sourceable c2 USING (space, node_external_id)
  LEFT JOIN cdf_cdm.cognite_asset c3 USING (space, node_external_id)
 WHERE NOT n.deleted;

CREATE OR REPLACE VIEW dm_dom_well_production.well_intervention_v1 AS
SELECT
  n.space,
  n.node_external_id,
  c1.name,
  c1.description,
  c2.start_time,
  c2.end_time,
  c2.scheduled_start_time,
  c3.status,
  c3.priority,
  c3.main_asset,
  n.intervention_type,
  n.estimated_uplift_bpd
  FROM dm_dom_well_production.well_intervention n
  LEFT JOIN cdf_cdm.cognite_describable c1 USING (space, node_external_id)
  LEFT JOIN cdf_cdm.cognite_schedulable c2 USING (space, node_external_id)
  LEFT JOIN cdf_idm.cognite_maintenance_order c3 USING (space, node_external_id)
 WHERE NOT n.deleted;

CREATE OR REPLACE VIEW dm_sol_production_analytics.well_production_daily_v1 AS
SELECT
  n.space,
  n.node_external_id,
  n.production_date,
  n.wellbore,
  n.well,
  n.field,
  n.well_name,
  n.field_name,
  n.oil_bbl,
  n.gas_mscf,
  n.water_bbl,
  n.water_cut_pct,
  n.gas_oil_ratio,
  n.avg_tubing_head_pressure_bar,
  n.uptime_hours,
  n.reading_count,
  n.intervention_count,
  n.computed_at
  FROM dm_sol_production_analytics.well_production_daily n
 WHERE NOT n.deleted;

-- The knowledge graph itself. scripts/compile-model.py is its only writer;

-- semantic.resolve() is its only reader. Reloaded wholesale so this file stays

-- re-appliable against a running database.

DELETE FROM semantic.data_model_views;

DELETE FROM semantic.data_models;

DELETE FROM semantic.view_properties;

DELETE FROM semantic.view_implements;

DELETE FROM semantic.views;

DELETE FROM semantic.container_properties;

DELETE FROM semantic.containers;

DELETE FROM semantic.spaces;

INSERT INTO semantic.spaces
    (space, kind, name, description)
VALUES
    ('cdf_cdm', 'schema', 'cdf_cdm', 'Cognite system space.'),
    ('cdf_idm', 'schema', 'cdf_idm', 'Cognite system space.'),
    ('dm_dom_well_production', 'schema', 'Well production DM DOM', 'Enterprise schema space holding the well production domain model.'),
    ('dm_sol_production_analytics', 'schema', 'Production analytics DM SOL', 'Solution schema space for the production surveillance use case.'),
    ('inst_well_production', 'instance', 'Well production instance space', 'Instance space holding all well production nodes and records.');

INSERT INTO semantic.containers
    (space, external_id, used_for, relation, name, description)
VALUES
    ('cdf_cdm', 'CogniteAsset', 'node', 'cdf_cdm.cognite_asset', 'Cognite asset', 'Cognite core type representing a physical or functional asset, and the hierarchy it belongs to.'),
    ('cdf_cdm', 'CogniteAssetType', 'node', 'cdf_cdm.cognite_asset_type', 'Cognite asset type', 'Cognite core type classifying assets, for example field, well or wellbore.'),
    ('cdf_cdm', 'CogniteDescribable', 'node', 'cdf_cdm.cognite_describable', 'Cognite describable', 'Cognite core feature giving an instance a name, description, tags and aliases.'),
    ('cdf_cdm', 'CogniteSchedulable', 'node', 'cdf_cdm.cognite_schedulable', 'Cognite schedulable', 'Cognite core feature giving an instance planned and actual start and end times.'),
    ('cdf_cdm', 'CogniteSourceable', 'node', 'cdf_cdm.cognite_sourceable', 'Cognite sourceable', 'Cognite core feature recording where an instance came from in a source system.'),
    ('cdf_idm', 'CogniteMaintenanceOrder', 'node', 'cdf_idm.cognite_maintenance_order', 'Cognite maintenance order', 'Cognite industrial type representing a maintenance order raised against an asset.'),
    ('dm_dom_well_production', 'Asset', 'node', 'dm_dom_well_production.asset', 'Asset', 'Well production asset hierarchy node - a field, a well, or a wellbore.'),
    ('dm_dom_well_production', 'ProductionMeasurement', 'record', 'dm_dom_well_production.production_measurement', 'Production measurement', 'High-volume metered production reading taken at a wellbore at a point in time.'),
    ('dm_dom_well_production', 'WellIntervention', 'node', 'dm_dom_well_production.well_intervention', 'Well intervention', 'Maintenance or remedial work carried out on a well to restore or improve production.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'node', 'dm_sol_production_analytics.well_production_daily', 'Well production daily', 'Daily production aggregate per wellbore, denormalised for one-shot dashboard reads.');

INSERT INTO semantic.container_properties
    (space, container, identifier, data_type, is_list, nullable, column_name, pg_type, name, description)
VALUES
    ('cdf_cdm', 'CogniteAsset', 'assetHierarchy_parent', 'direct', false, true, 'asset_hierarchy_parent', 'text', 'Parent', 'The parent of the asset.'),
    ('cdf_cdm', 'CogniteAsset', 'assetHierarchy_root', 'direct', false, true, 'asset_hierarchy_root', 'text', 'Root', 'An automatically updated reference to the top-level asset of the hierarchy.'),
    ('cdf_cdm', 'CogniteAsset', 'assetHierarchy_path', 'direct', true, true, 'asset_hierarchy_path', 'text[]', 'Path', 'An automatically updated ordered list of this asset''s ancestors, starting with the root asset. Enables subtree filtering to find all assets under a parent.'),
    ('cdf_cdm', 'CogniteAsset', 'assetHierarchy_pathLastUpdatedTime', 'timestamp', false, true, 'asset_hierarchy_path_last_updated_time', 'timestamptz', 'Path last updated time', 'The last time the path property was updated.'),
    ('cdf_cdm', 'CogniteAsset', 'assetClass', 'direct', false, true, 'asset_class', 'text', 'Asset class', 'Specifies the class of the asset. It''s a direct relation to CogniteAssetClass.'),
    ('cdf_cdm', 'CogniteAsset', 'type', 'direct', false, true, 'type', 'text', 'Asset type', 'Specifies the type of the asset. It''s a direct relation to CogniteAssetType.'),
    ('cdf_cdm', 'CogniteAssetType', 'code', 'text', false, true, 'code', 'text', 'Code', 'A unique identifier for the type of asset.'),
    ('cdf_cdm', 'CogniteAssetType', 'assetClass', 'direct', false, true, 'asset_class', 'text', 'Asset class', 'Specifies the class the type belongs to. It''s a direct relation to CogniteAssetClass.'),
    ('cdf_cdm', 'CogniteDescribable', 'name', 'text', false, true, 'name', 'text', 'Name', 'Name of the instance.'),
    ('cdf_cdm', 'CogniteDescribable', 'description', 'text', false, true, 'description', 'text', 'Description', 'Description of the instance.'),
    ('cdf_cdm', 'CogniteDescribable', 'tags', 'text', true, true, 'tags', 'text[]', 'Tags', 'Text based labels for generic use, limited to 1000 per instance.'),
    ('cdf_cdm', 'CogniteDescribable', 'aliases', 'text', true, true, 'aliases', 'text[]', 'Aliases', 'Alternative names for the node.'),
    ('cdf_cdm', 'CogniteSchedulable', 'startTime', 'timestamp', false, true, 'start_time', 'timestamptz', 'Start time', 'The actual start time of an activity (or similar that extends this).'),
    ('cdf_cdm', 'CogniteSchedulable', 'endTime', 'timestamp', false, true, 'end_time', 'timestamptz', 'End time', 'The actual end time of an activity (or similar that extends this).'),
    ('cdf_cdm', 'CogniteSchedulable', 'scheduledStartTime', 'timestamp', false, true, 'scheduled_start_time', 'timestamptz', 'Scheduled start time', 'The planned start time of an activity (or similar that extends this).'),
    ('cdf_cdm', 'CogniteSchedulable', 'scheduledEndTime', 'timestamp', false, true, 'scheduled_end_time', 'timestamptz', 'Scheduled end time', 'The planned end time of an activity (or similar that extends this).'),
    ('cdf_cdm', 'CogniteSourceable', 'sourceId', 'text', false, true, 'source_id', 'text', 'Source ID', 'Identifier from the source system.'),
    ('cdf_cdm', 'CogniteSourceable', 'sourceContext', 'text', false, true, 'source_context', 'text', 'Source context', 'Context of the source id. For systems where the source id is globally unique, the source is more than sufficient to identify the object.'),
    ('cdf_cdm', 'CogniteSourceable', 'sourceCreatedTime', 'timestamp', false, true, 'source_created_time', 'timestamptz', 'Source created time', 'When the instance was created in the source system.'),
    ('cdf_cdm', 'CogniteSourceable', 'sourceUpdatedTime', 'timestamp', false, true, 'source_updated_time', 'timestamptz', 'Source updated time', 'When the instance was last updated in the source system.'),
    ('cdf_idm', 'CogniteMaintenanceOrder', 'mainAsset', 'direct', false, true, 'main_asset', 'text', 'Main asset', 'The primary asset the maintenance order was raised against.'),
    ('cdf_idm', 'CogniteMaintenanceOrder', 'type', 'text', false, true, 'type', 'text', 'Type', 'Source system defined type of the maintenance order.'),
    ('cdf_idm', 'CogniteMaintenanceOrder', 'status', 'text', false, true, 'status', 'text', 'Status', 'Source system defined status of the maintenance order.'),
    ('cdf_idm', 'CogniteMaintenanceOrder', 'priority', 'int32', false, true, 'priority', 'integer', 'Priority', 'Numeric priority of the maintenance order, lower is more urgent.'),
    ('cdf_idm', 'CogniteMaintenanceOrder', 'priorityDescription', 'text', false, true, 'priority_description', 'text', 'Priority description', 'Human readable description of the priority.'),
    ('dm_dom_well_production', 'Asset', 'assetType', 'text', false, false, 'asset_type', 'text', 'Asset type', 'Level of this node in the production hierarchy - field, well or wellbore.'),
    ('dm_dom_well_production', 'Asset', 'wellId', 'text', false, true, 'well_id', 'text', 'Well ID', 'Unique well identifier (UWI) issued by the licensing authority.'),
    ('dm_dom_well_production', 'Asset', 'fieldCode', 'text', false, true, 'field_code', 'text', 'Field code', 'Short operator code for the producing field, for example FLD-DRA.'),
    ('dm_dom_well_production', 'Asset', 'wellType', 'text', false, true, 'well_type', 'text', 'Well type', 'Operational role of the well, for example producer or water injector.'),
    ('dm_dom_well_production', 'Asset', 'spudDate', 'date', false, true, 'spud_date', 'date', 'Spud date', 'Date on which drilling of the well commenced.'),
    ('dm_dom_well_production', 'Asset', 'waterDepthM', 'float64', false, true, 'water_depth_m', 'double precision', 'Water depth (m)', 'Water depth at the surface location, in metres.'),
    ('dm_dom_well_production', 'Asset', 'totalDepthM', 'float64', false, true, 'total_depth_m', 'double precision', 'Total depth (m)', 'Measured total depth of the wellbore, in metres.'),
    ('dm_dom_well_production', 'Asset', 'completionType', 'text', false, true, 'completion_type', 'text', 'Completion type', 'Completion design of the wellbore, for example cased hole or open hole.'),
    ('dm_dom_well_production', 'ProductionMeasurement', 'wellbore', 'direct', false, false, 'wellbore', 'text', 'Wellbore', 'The wellbore this reading was metered at.'),
    ('dm_dom_well_production', 'ProductionMeasurement', 'measuredAt', 'timestamp', false, false, 'measured_at', 'timestamptz', 'Measured at', 'Timestamp at which the reading was taken.'),
    ('dm_dom_well_production', 'ProductionMeasurement', 'oilRateBpd', 'float64', false, true, 'oil_rate_bpd', 'double precision', 'Oil rate (bpd)', 'Instantaneous oil production rate, in barrels per day.'),
    ('dm_dom_well_production', 'ProductionMeasurement', 'gasRateMscfd', 'float64', false, true, 'gas_rate_mscfd', 'double precision', 'Gas rate (Mscf/d)', 'Instantaneous gas production rate, in thousand standard cubic feet per day.'),
    ('dm_dom_well_production', 'ProductionMeasurement', 'waterRateBpd', 'float64', false, true, 'water_rate_bpd', 'double precision', 'Water rate (bpd)', 'Instantaneous produced water rate, in barrels per day.'),
    ('dm_dom_well_production', 'ProductionMeasurement', 'tubingHeadPressureBar', 'float64', false, true, 'tubing_head_pressure_bar', 'double precision', 'Tubing head pressure (bar)', 'Pressure measured at the tubing head at the time of the reading, in bar.'),
    ('dm_dom_well_production', 'ProductionMeasurement', 'chokePercent', 'float64', false, true, 'choke_percent', 'double precision', 'Choke opening (%)', 'Production choke opening at the time of the reading, as a percentage.'),
    ('dm_dom_well_production', 'ProductionMeasurement', 'quality', 'text', false, true, 'quality', 'text', 'Reading quality', 'Metering quality flag - good, suspect or bad - used to compute uptime.'),
    ('dm_dom_well_production', 'WellIntervention', 'interventionType', 'text', false, true, 'intervention_type', 'text', 'Intervention type', 'Category of intervention, for example ESP replacement or coiled tubing cleanout.'),
    ('dm_dom_well_production', 'WellIntervention', 'estimatedUpliftBpd', 'float64', false, true, 'estimated_uplift_bpd', 'double precision', 'Estimated uplift (bpd)', 'Expected production gain from the intervention, in barrels per day.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'productionDate', 'date', false, false, 'production_date', 'date', 'Production date', 'Calendar day (UTC) the readings were aggregated over.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'wellbore', 'direct', false, false, 'wellbore', 'text', 'Wellbore', 'The wellbore this daily aggregate belongs to.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'well', 'direct', false, true, 'well', 'text', 'Well', 'Parent well of the wellbore, denormalised to avoid a traversal hop.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'field', 'direct', false, true, 'field', 'text', 'Field', 'Producing field of the well, denormalised to avoid two traversal hops.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'wellName', 'text', false, true, 'well_name', 'text', 'Well name', 'Operational name of the parent well, copied from the enterprise model at build time.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'fieldName', 'text', false, true, 'field_name', 'text', 'Field name', 'Name of the producing field, copied from the enterprise model at build time.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'oilBbl', 'float64', false, true, 'oil_bbl', 'double precision', 'Oil volume (bbl)', 'Oil volume produced over the day, in barrels.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'gasMscf', 'float64', false, true, 'gas_mscf', 'double precision', 'Gas volume (Mscf)', 'Gas volume produced over the day, in thousand standard cubic feet.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'waterBbl', 'float64', false, true, 'water_bbl', 'double precision', 'Water volume (bbl)', 'Produced water volume over the day, in barrels.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'waterCutPct', 'float64', false, true, 'water_cut_pct', 'double precision', 'Water cut (%)', 'Water as a percentage of total produced liquid over the day.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'gasOilRatio', 'float64', false, true, 'gas_oil_ratio', 'double precision', 'Gas-oil ratio (scf/bbl)', 'Produced gas per barrel of oil over the day, in standard cubic feet per barrel.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'avgTubingHeadPressureBar', 'float64', false, true, 'avg_tubing_head_pressure_bar', 'double precision', 'Average tubing head pressure (bar)', 'Mean tubing head pressure across the day''s readings, in bar.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'uptimeHours', 'float64', false, true, 'uptime_hours', 'double precision', 'Uptime (hours)', 'Hours in the day with a good-quality metering reading.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'readingCount', 'int64', false, true, 'reading_count', 'bigint', 'Reading count', 'Number of metering readings aggregated into this row.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'interventionCount', 'int64', false, true, 'intervention_count', 'bigint', 'Intervention count', 'Well interventions active on the parent well during this day.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'computedAt', 'timestamp', false, false, 'computed_at', 'timestamptz', 'Computed at', 'Timestamp at which the analytical job produced this row.');

INSERT INTO semantic.views
    (space, external_id, version, relation, anchor_space, anchor_container, name, description)
VALUES
    ('cdf_cdm', 'CogniteAssetType', 'v1', 'cdf_cdm.cognite_asset_type_v1', 'cdf_cdm', 'CogniteAssetType', 'Asset type', 'Classification of an asset - in this model, field, well or wellbore.'),
    ('dm_dom_well_production', 'Asset', 'v1', 'dm_dom_well_production.asset_v1', 'dm_dom_well_production', 'Asset', 'Asset', 'Production asset hierarchy - fields, wells and wellbores as a single CogniteAsset hierarchy, with licensing identity, drilling context and completion detail. The one CogniteAsset implementer of WellProduction_DOM.'),
    ('dm_dom_well_production', 'WellIntervention', 'v1', 'dm_dom_well_production.well_intervention_v1', 'dm_dom_well_production', 'WellIntervention', 'Well intervention', 'Maintenance and remedial work carried out on a well, including schedule, status, priority and the expected production uplift.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'v1', 'dm_sol_production_analytics.well_production_daily_v1', 'dm_sol_production_analytics', 'WellProductionDaily', 'Well production daily', 'Daily production per wellbore with well and field context denormalised onto every row, so a dashboard reads a day of production in a single query with no traversal.');

INSERT INTO semantic.view_implements
    (space, external_id, version, seq, parent_space, parent_external_id, parent_version)
VALUES
    ('cdf_cdm', 'CogniteAssetType', 'v1', 0, 'cdf_cdm', 'CogniteDescribable', 'v1'),
    ('dm_dom_well_production', 'Asset', 'v1', 0, 'cdf_cdm', 'CogniteAsset', 'v1'),
    ('dm_dom_well_production', 'WellIntervention', 'v1', 0, 'cdf_idm', 'CogniteMaintenanceOrder', 'v1');

INSERT INTO semantic.view_properties
    (space, external_id, version, identifier, kind, container_space, container_external_id, container_identifier, column_name, pg_type, source_space, source_external_id, source_version, through_space, through_external_id, through_version, through_identifier, inherited_from, name, description)
VALUES
    ('cdf_cdm', 'CogniteAssetType', 'v1', 'name', 'primitive', 'cdf_cdm', 'CogniteDescribable', 'name', 'name', 'text', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Name', 'Human readable name of the asset type.'),
    ('cdf_cdm', 'CogniteAssetType', 'v1', 'description', 'primitive', 'cdf_cdm', 'CogniteDescribable', 'description', 'description', 'text', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Description', 'Description of what this asset type represents.'),
    ('cdf_cdm', 'CogniteAssetType', 'v1', 'code', 'primitive', 'cdf_cdm', 'CogniteAssetType', 'code', 'code', 'text', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Code', 'A unique identifier for the type of asset.'),
    ('dm_dom_well_production', 'Asset', 'v1', 'name', 'primitive', 'cdf_cdm', 'CogniteDescribable', 'name', 'name', 'text', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Name', 'Common operational name of the asset, for example DRA-A1.'),
    ('dm_dom_well_production', 'Asset', 'v1', 'description', 'primitive', 'cdf_cdm', 'CogniteDescribable', 'description', 'description', 'text', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Description', 'Free-text description of the asset.'),
    ('dm_dom_well_production', 'Asset', 'v1', 'labels', 'primitive', 'cdf_cdm', 'CogniteDescribable', 'tags', 'labels', 'text[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Labels', 'Text labels on the asset. Aliased from CogniteDescribable.tags to avoid confusion with the direct relations on this view.'),
    ('dm_dom_well_production', 'Asset', 'v1', 'aliases', 'primitive', 'cdf_cdm', 'CogniteDescribable', 'aliases', 'aliases', 'text[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Aliases', 'Alternative names the asset is known by in source systems.'),
    ('dm_dom_well_production', 'Asset', 'v1', 'sourceId', 'primitive', 'cdf_cdm', 'CogniteSourceable', 'sourceId', 'source_id', 'text', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Source ID', 'Identifier of the asset in the production accounting source system.'),
    ('dm_dom_well_production', 'Asset', 'v1', 'sourceContext', 'primitive', 'cdf_cdm', 'CogniteSourceable', 'sourceContext', 'source_context', 'text', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Source context', 'Context within the source system that qualifies the source ID.'),
    ('dm_dom_well_production', 'Asset', 'v1', 'sourceCreatedTime', 'primitive', 'cdf_cdm', 'CogniteSourceable', 'sourceCreatedTime', 'source_created_time', 'timestamptz', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Source created time', 'Time the asset record was created in the source system.'),
    ('dm_dom_well_production', 'Asset', 'v1', 'parent', 'direct', 'cdf_cdm', 'CogniteAsset', 'assetHierarchy_parent', 'parent', 'text', 'dm_dom_well_production', 'Asset', 'v1', NULL, NULL, NULL, NULL, NULL, 'Parent', 'Parent of this asset - a well''s parent is its field, a wellbore''s is its well.'),
    ('dm_dom_well_production', 'Asset', 'v1', 'root', 'direct', 'cdf_cdm', 'CogniteAsset', 'assetHierarchy_root', 'root', 'text', 'dm_dom_well_production', 'Asset', 'v1', NULL, NULL, NULL, NULL, NULL, 'Root', 'Automatically maintained reference to the field at the top of this hierarchy.'),
    ('dm_dom_well_production', 'Asset', 'v1', 'path', 'direct', 'cdf_cdm', 'CogniteAsset', 'assetHierarchy_path', 'path', 'text[]', 'dm_dom_well_production', 'Asset', 'v1', NULL, NULL, NULL, NULL, NULL, 'Path', 'Ordered ancestor chain from the root field down to this asset, enabling subtree filtering across the whole hierarchy.'),
    ('dm_dom_well_production', 'Asset', 'v1', 'type', 'direct', 'cdf_cdm', 'CogniteAsset', 'type', 'type', 'text', 'cdf_cdm', 'CogniteAssetType', 'v1', NULL, NULL, NULL, NULL, NULL, 'Asset type', 'CDM asset type distinguishing field, well and wellbore nodes.'),
    ('dm_dom_well_production', 'Asset', 'v1', 'assetType', 'primitive', 'dm_dom_well_production', 'Asset', 'assetType', 'asset_type', 'text', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asset level', 'Level of this node in the production hierarchy - field, well or wellbore.'),
    ('dm_dom_well_production', 'Asset', 'v1', 'wellId', 'primitive', 'dm_dom_well_production', 'Asset', 'wellId', 'well_id', 'text', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Well ID', 'Unique well identifier (UWI) issued by the licensing authority.'),
    ('dm_dom_well_production', 'Asset', 'v1', 'fieldCode', 'primitive', 'dm_dom_well_production', 'Asset', 'fieldCode', 'field_code', 'text', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Field code', 'Short operator code for the producing field, for example FLD-DRA.'),
    ('dm_dom_well_production', 'Asset', 'v1', 'wellType', 'primitive', 'dm_dom_well_production', 'Asset', 'wellType', 'well_type', 'text', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Well type', 'Operational role of the well, for example producer or water injector.'),
    ('dm_dom_well_production', 'Asset', 'v1', 'spudDate', 'primitive', 'dm_dom_well_production', 'Asset', 'spudDate', 'spud_date', 'date', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Spud date', 'Date on which drilling of the well commenced.'),
    ('dm_dom_well_production', 'Asset', 'v1', 'waterDepthM', 'primitive', 'dm_dom_well_production', 'Asset', 'waterDepthM', 'water_depth_m', 'double precision', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Water depth (m)', 'Water depth at the surface location, in metres.'),
    ('dm_dom_well_production', 'Asset', 'v1', 'totalDepthM', 'primitive', 'dm_dom_well_production', 'Asset', 'totalDepthM', 'total_depth_m', 'double precision', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Total depth (m)', 'Measured total depth of the wellbore, in metres.'),
    ('dm_dom_well_production', 'Asset', 'v1', 'completionType', 'primitive', 'dm_dom_well_production', 'Asset', 'completionType', 'completion_type', 'text', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Completion type', 'Completion design of the wellbore, for example cased hole or open hole.'),
    ('dm_dom_well_production', 'Asset', 'v1', 'children', 'multi_reverse_direct_relation', NULL, NULL, NULL, NULL, NULL, 'dm_dom_well_production', 'Asset', 'v1', 'dm_dom_well_production', 'Asset', 'v1', 'parent', NULL, 'Children', 'Assets directly below this one in the hierarchy - a field''s wells, a well''s wellbores.'),
    ('dm_dom_well_production', 'Asset', 'v1', 'interventions', 'multi_reverse_direct_relation', NULL, NULL, NULL, NULL, NULL, 'dm_dom_well_production', 'WellIntervention', 'v1', 'dm_dom_well_production', 'WellIntervention', 'v1', 'mainAsset', NULL, 'Interventions', 'Well interventions raised against this asset as their primary asset.'),
    ('dm_dom_well_production', 'WellIntervention', 'v1', 'name', 'primitive', 'cdf_cdm', 'CogniteDescribable', 'name', 'name', 'text', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Name', 'Short title of the intervention, for example Draugen A-1 ESP replacement.'),
    ('dm_dom_well_production', 'WellIntervention', 'v1', 'description', 'primitive', 'cdf_cdm', 'CogniteDescribable', 'description', 'description', 'text', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Description', 'Scope of work for the intervention.'),
    ('dm_dom_well_production', 'WellIntervention', 'v1', 'startTime', 'primitive', 'cdf_cdm', 'CogniteSchedulable', 'startTime', 'start_time', 'timestamptz', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Start time', 'Actual time work on the intervention started.'),
    ('dm_dom_well_production', 'WellIntervention', 'v1', 'endTime', 'primitive', 'cdf_cdm', 'CogniteSchedulable', 'endTime', 'end_time', 'timestamptz', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'End time', 'Actual time work on the intervention finished.'),
    ('dm_dom_well_production', 'WellIntervention', 'v1', 'scheduledStartTime', 'primitive', 'cdf_cdm', 'CogniteSchedulable', 'scheduledStartTime', 'scheduled_start_time', 'timestamptz', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Scheduled start time', 'Planned start time of the intervention.'),
    ('dm_dom_well_production', 'WellIntervention', 'v1', 'status', 'primitive', 'cdf_idm', 'CogniteMaintenanceOrder', 'status', 'status', 'text', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Status', 'Workflow status of the intervention, for example planned, active or complete.'),
    ('dm_dom_well_production', 'WellIntervention', 'v1', 'priority', 'primitive', 'cdf_idm', 'CogniteMaintenanceOrder', 'priority', 'priority', 'integer', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Priority', 'Numeric priority of the intervention, lower is more urgent.'),
    ('dm_dom_well_production', 'WellIntervention', 'v1', 'mainAsset', 'direct', 'cdf_idm', 'CogniteMaintenanceOrder', 'mainAsset', 'main_asset', 'text', 'dm_dom_well_production', 'Asset', 'v1', NULL, NULL, NULL, NULL, NULL, 'Main asset', 'The well this intervention was raised against.'),
    ('dm_dom_well_production', 'WellIntervention', 'v1', 'interventionType', 'primitive', 'dm_dom_well_production', 'WellIntervention', 'interventionType', 'intervention_type', 'text', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Intervention type', 'Category of intervention, for example ESP replacement or coiled tubing cleanout.'),
    ('dm_dom_well_production', 'WellIntervention', 'v1', 'estimatedUpliftBpd', 'primitive', 'dm_dom_well_production', 'WellIntervention', 'estimatedUpliftBpd', 'estimated_uplift_bpd', 'double precision', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Estimated uplift (bpd)', 'Expected production gain from the intervention, in barrels per day.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'v1', 'productionDate', 'primitive', 'dm_sol_production_analytics', 'WellProductionDaily', 'productionDate', 'production_date', 'date', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Production date', 'Calendar day (UTC) the readings were aggregated over.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'v1', 'wellbore', 'direct', 'dm_sol_production_analytics', 'WellProductionDaily', 'wellbore', 'wellbore', 'text', 'dm_dom_well_production', 'Asset', 'v1', NULL, NULL, NULL, NULL, NULL, 'Wellbore', 'The wellbore this daily aggregate belongs to.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'v1', 'well', 'direct', 'dm_sol_production_analytics', 'WellProductionDaily', 'well', 'well', 'text', 'dm_dom_well_production', 'Asset', 'v1', NULL, NULL, NULL, NULL, NULL, 'Well', 'Parent well of the wellbore, denormalised to avoid a traversal hop.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'v1', 'field', 'direct', 'dm_sol_production_analytics', 'WellProductionDaily', 'field', 'field', 'text', 'dm_dom_well_production', 'Asset', 'v1', NULL, NULL, NULL, NULL, NULL, 'Field', 'Producing field of the well, denormalised to avoid two traversal hops.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'v1', 'wellName', 'primitive', 'dm_sol_production_analytics', 'WellProductionDaily', 'wellName', 'well_name', 'text', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Well name', 'Operational name of the parent well, recomputed from the enterprise model on every build.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'v1', 'fieldName', 'primitive', 'dm_sol_production_analytics', 'WellProductionDaily', 'fieldName', 'field_name', 'text', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Field name', 'Name of the producing field, recomputed from the enterprise model on every build.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'v1', 'oilBbl', 'primitive', 'dm_sol_production_analytics', 'WellProductionDaily', 'oilBbl', 'oil_bbl', 'double precision', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Oil volume (bbl)', 'Oil volume produced over the day, in barrels.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'v1', 'gasMscf', 'primitive', 'dm_sol_production_analytics', 'WellProductionDaily', 'gasMscf', 'gas_mscf', 'double precision', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Gas volume (Mscf)', 'Gas volume produced over the day, in thousand standard cubic feet.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'v1', 'waterBbl', 'primitive', 'dm_sol_production_analytics', 'WellProductionDaily', 'waterBbl', 'water_bbl', 'double precision', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Water volume (bbl)', 'Produced water volume over the day, in barrels.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'v1', 'waterCutPct', 'primitive', 'dm_sol_production_analytics', 'WellProductionDaily', 'waterCutPct', 'water_cut_pct', 'double precision', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Water cut (%)', 'Water as a percentage of total produced liquid over the day.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'v1', 'gasOilRatio', 'primitive', 'dm_sol_production_analytics', 'WellProductionDaily', 'gasOilRatio', 'gas_oil_ratio', 'double precision', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Gas-oil ratio (scf/bbl)', 'Produced gas per barrel of oil over the day, in standard cubic feet per barrel.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'v1', 'avgTubingHeadPressureBar', 'primitive', 'dm_sol_production_analytics', 'WellProductionDaily', 'avgTubingHeadPressureBar', 'avg_tubing_head_pressure_bar', 'double precision', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Average tubing head pressure (bar)', 'Mean tubing head pressure across the day''s readings, in bar.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'v1', 'uptimeHours', 'primitive', 'dm_sol_production_analytics', 'WellProductionDaily', 'uptimeHours', 'uptime_hours', 'double precision', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Uptime (hours)', 'Hours in the day with a good-quality metering reading.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'v1', 'readingCount', 'primitive', 'dm_sol_production_analytics', 'WellProductionDaily', 'readingCount', 'reading_count', 'bigint', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Reading count', 'Number of metering readings aggregated into this row.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'v1', 'interventionCount', 'primitive', 'dm_sol_production_analytics', 'WellProductionDaily', 'interventionCount', 'intervention_count', 'bigint', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Intervention count', 'Well interventions active on the parent well during this day, derived by traversing the enterprise model at build time.'),
    ('dm_sol_production_analytics', 'WellProductionDaily', 'v1', 'computedAt', 'primitive', 'dm_sol_production_analytics', 'WellProductionDaily', 'computedAt', 'computed_at', 'timestamptz', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Computed at', 'Timestamp at which the analytical job produced this row.');

INSERT INTO semantic.data_models
    (space, external_id, version, name, description)
VALUES
    ('dm_dom_well_production', 'WellProduction_DOM', 'v1', 'Well production DOM', 'Enterprise model for oil and gas well production - asset hierarchy and interventions.'),
    ('dm_sol_production_analytics', 'ProductionAnalytics_SOL', 'v1', 'Production analytics SOL', 'Solution model serving daily production surveillance dashboards.');

INSERT INTO semantic.data_model_views
    (space, external_id, version, view_space, view_external_id, view_version)
VALUES
    ('dm_dom_well_production', 'WellProduction_DOM', 'v1', 'dm_dom_well_production', 'Asset', 'v1'),
    ('dm_dom_well_production', 'WellProduction_DOM', 'v1', 'dm_dom_well_production', 'WellIntervention', 'v1'),
    ('dm_dom_well_production', 'WellProduction_DOM', 'v1', 'cdf_cdm', 'CogniteAssetType', 'v1'),
    ('dm_sol_production_analytics', 'ProductionAnalytics_SOL', 'v1', 'dm_sol_production_analytics', 'WellProductionDaily', 'v1');
