\set ON_ERROR_STOP on

-- The analytical job that promotes normalised EDM data into the denormalised SDM view.
--
-- It lives in `aetherlake`, not in a model schema: the model schemas are entirely generated by
-- scripts/compile-model.py, and a hand-written procedure inside one would break `make
-- model-check`. `aetherlake` is already the hand-written orchestration schema.
--
-- It reads the compiled EDM *views*, not the container tables - so "the job consumes the
-- semantic layer" is literally true. The one exception is ProductionMeasurement, a
-- usedFor: record container, which by design has no view: the semantic layer covers the graph,
-- and the job reaches below it into the record store.

CREATE TABLE IF NOT EXISTS aetherlake.sdm_build_log (
    build_id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    target           text        NOT NULL,
    window_from      date        NOT NULL,
    window_to        date        NOT NULL,
    source_views     text[]      NOT NULL,
    source_snapshots jsonb       NOT NULL,
    snapshot_before  bigint,
    snapshot_after   bigint,
    rows_written     bigint      NOT NULL,
    duration_ms      numeric     NOT NULL,
    built_at         timestamptz NOT NULL DEFAULT clock_timestamp()
) USING heap;

CREATE OR REPLACE PROCEDURE aetherlake.build_well_production_daily(
    p_from date DEFAULT current_date - 90,
    p_to   date DEFAULT current_date + 1
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, aetherlake
AS $$
DECLARE
    started       timestamptz := clock_timestamp();
    snap_before   bigint;
    src_snapshots jsonb;
    written       bigint;
BEGIN
    -- Same mutual-exclusion contract as sync_historical_deltas: never block, just skip.
    IF NOT pg_try_advisory_xact_lock(hashtextextended('aetherlake.sdm-well-production-daily', 0)) THEN
        RAISE NOTICE 'AetherLake SDM build is already running';
        RETURN;
    END IF;

    SELECT jsonb_object_agg(t.table_namespace || '.' || t.table_name,
                            lake_iceberg.metadata(t.metadata_location) -> 'current-snapshot-id')
      INTO src_snapshots
      FROM iceberg_tables t
     WHERE t.table_namespace IN ('dm_dom_well_production', 'cdf_cdm', 'cdf_idm');

    snap_before := semantic.snapshot_id('dm_sol_production_analytics.well_production_daily');

    -- pg_lake publishes an Iceberg snapshot at COMMIT, so a transaction can only ever see the
    -- snapshot it started from - this build cannot observe its own result. Each run therefore
    -- closes out the previous one: the snapshot we are starting from is exactly what the last
    -- build produced. The log is self-closing, and it works identically from cron, psql and
    -- the console.
    UPDATE aetherlake.sdm_build_log
       SET snapshot_after = snap_before
     WHERE snapshot_after IS NULL
       AND target = 'dm_sol_production_analytics:WellProductionDaily/v1';

    -- pg_lake supports DELETE on Iceberg tables but not MERGE or ON CONFLICT, so
    -- delete-then-insert over a bounded window is the idempotency primitive.
    DELETE FROM dm_sol_production_analytics.well_production_daily
     WHERE production_date >= p_from AND production_date < p_to;

    WITH readings AS (
        SELECT m.wellbore,
               (m.measured_at AT TIME ZONE 'UTC')::date AS production_date,
               m.oil_rate_bpd, m.gas_rate_mscfd, m.water_rate_bpd,
               m.tubing_head_pressure_bar, m.quality
          FROM dm_dom_well_production.production_measurement m
         WHERE m.measured_at >= p_from::timestamptz
           AND m.measured_at <  p_to::timestamptz
    ), daily AS (
        SELECT wellbore,
               production_date,
               sum(oil_rate_bpd)   / 24.0 AS oil_bbl,
               sum(gas_rate_mscfd) / 24.0 AS gas_mscf,
               sum(water_rate_bpd) / 24.0 AS water_bbl,
               avg(tubing_head_pressure_bar) AS avg_thp_bar,
               count(*) FILTER (WHERE quality = 'good')::double precision AS uptime_hours,
               count(*) AS reading_count
          FROM readings
         GROUP BY 1, 2
    )
    INSERT INTO dm_sol_production_analytics.well_production_daily (
        space, node_external_id, production_date, wellbore, well, field,
        well_name, field_name, oil_bbl, gas_mscf, water_bbl, water_cut_pct, gas_oil_ratio,
        avg_tubing_head_pressure_bar, uptime_hours, reading_count, intervention_count, computed_at)
    SELECT wb.space,
           d.wellbore || ':' || to_char(d.production_date, 'YYYY-MM-DD'),
           d.production_date,
           d.wellbore,
           w.node_external_id,
           f.node_external_id,
           w.name,
           f.name,
           d.oil_bbl, d.gas_mscf, d.water_bbl,
           CASE WHEN d.oil_bbl + d.water_bbl > 0
                THEN 100.0 * d.water_bbl / (d.oil_bbl + d.water_bbl) END,
           CASE WHEN d.oil_bbl > 0 THEN 1000.0 * d.gas_mscf / d.oil_bbl END,
           d.avg_thp_bar,
           d.uptime_hours,
           d.reading_count,
           coalesce(i.intervention_count, 0),
           clock_timestamp()
      FROM daily d
      JOIN dm_dom_well_production.asset_v1 wb ON wb.node_external_id = d.wellbore
      JOIN dm_dom_well_production.asset_v1 w  ON w.node_external_id  = wb.parent
      JOIN dm_dom_well_production.asset_v1 f  ON f.node_external_id  = w.parent
      LEFT JOIN LATERAL (
           SELECT count(*) AS intervention_count
             FROM dm_dom_well_production.well_intervention_v1 wi
            WHERE wi.main_asset = w.node_external_id
              AND wi.start_time <  (d.production_date + 1)::timestamptz
              AND coalesce(wi.end_time, 'infinity'::timestamptz) >= d.production_date::timestamptz
      ) i ON true;

    GET DIAGNOSTICS written = ROW_COUNT;

    INSERT INTO aetherlake.sdm_build_log (
        target, window_from, window_to, source_views, source_snapshots,
        snapshot_before, snapshot_after, rows_written, duration_ms)
    VALUES (
        'dm_sol_production_analytics:WellProductionDaily/v1', p_from, p_to,
        ARRAY['dm_dom_well_production:Asset/v1',
              'dm_dom_well_production:WellIntervention/v1',
              'dm_dom_well_production:ProductionMeasurement (record container)'],
        -- snapshot_after stays null until the next run closes it out, or until a reader
        -- outside this transaction resolves the live snapshot.
        coalesce(src_snapshots, '{}'::jsonb), snap_before, NULL, written,
        round(extract(epoch FROM clock_timestamp() - started)::numeric * 1000, 1));
END
$$;

-- Named aetherlake-* so the demo console's existing `command LIKE '%aetherlake%'` job query
-- picks it up with no code change. cron.schedule upserts on jobname, so re-applying this file
-- against a running database is safe.
SELECT cron.schedule(
    'aetherlake-sdm-daily',
    :'sdm_cron',
    'CALL aetherlake.build_well_production_daily()'
);

GRANT SELECT ON aetherlake.sdm_build_log TO :"app_user";
